config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root "static_pages#home"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/index", to: "travellings#index"
  get "/show", to: "travellings#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  namespace :admin do
    root "static_pages#show"
    get "/locations", to: "locations#index"
    post "/locations", to: "locations#create"
    resources :users, only: %i(index destroy show)
    resources :locations, except: :show
    resources :travellings, except: :show
    resources :tours, except: :show
    resources :bookings, only: %i(index update)
    resources :export_users, only: :index
  end
  resources :users
  resources :travellings
  # resources :travellings do
  #   collection do
  #     match 'search' => "travellings#search", :via => [:get, :post], :as => :search
  #   end
  # end
  resources :tours
  resources :reviews

  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"

  resources :bookings, only: [:new, :create]
  delete "/delete", to: "bookings#destroy"
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :name
  after_validation :geocode, if: :name_changed?
  has_many :travellings_start_id, class_name: Travelling.name,
    foreign_key: :location_start, dependent: :destroy
  has_many :travellings_end_id, class_name: Travelling.name,
    foreign_key: :location_end, dependent: :destroy

  validates :name, uniqueness: true

  scope :ordered_by_name, ->{order name: :desc}
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminBaseController
  before_action :check_permission
  before_action :load_location, except: %i(index create)

  def edit; end

  def update
    if @location.update_attributes location_params
      flash[:success] = t "update_location_success"
      redirect_to admin_locations_path
    else
      flash[:danger] = t "update_location_failed"
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      if @location.destroy
        flash[:success] = t "del_location_success"
      else
        flash[:danger] = t "del_location_failed"
      end
      format.js
    end
  end

  def create
    @location = Location.new location_params
    respond_to do |format|
      if @location.save
        flash[:success] = t "add_location_success"
      else
        flash[:danger] = t "err_location"
      end
      format.js
    end
  end

  def index
    @location = Location.new
    @locations = Location.ordered_by_name.page(params[:page])
  end

  private

  def location_params
    params.require(:location).permit :name
  end

  def load_location
    @location = Location.find_by id: params[:id]
    return if @location
    flash[:danger] = t "err_location"
    redirect_to admin_locations_path
  end
end

app/views/admin/locations/_form.html.erb
<%= form_for [:admin, @location], remote: true, html: {class: "form-inline"} do |f| %>
  <div class="form-group mb-2">
    <%= f.label :name, t(".new"), class: "" %>
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.text_field :name, class: "form-control"  %>
  </div>
  <%= f.submit t(".submit"), class: "btn btn-primary mb-2" %>
<% end %>

app/views/admin/locations/_location.html.erb
<tr id="delete_location_<%= location.id %>">
  <td><%= location.id %></td>
  <td><%= location.name %></td>
  <td>
    <%= link_to t(".edit"), edit_admin_location_path(location), class: "btn btn-warning" %>
  </td>
  <td>
    <%= link_to t(".del"), admin_location_path(location), method: :delete, remote: true, class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/locations/create.js.erb
$('.locations').append("<%= j render @location %>")
<% flash.each do |message_type, message| %>
  $('#flash_messages').html("<div class='alert alert-<%= message_type %>'><%= message %>")
<% end %>

app/views/admin/locations/destroy.js.erb
$('#delete_location_<%= @location.id %>').remove();
<% flash.each do |message_type, message| %>
  $('#flash_messages').html("<div class='alert alert-<%= message_type %>'><%= message %>")
<% end %>

app/views/admin/locations/edit.html.erb
<%= form_for [:admin, @location], html: {class: "form-inline"} do |f| %>
  <div class="form-group mb-2">
    <%= f.label :name, t(".new"), class: "" %>
  </div>
  <div class="form-group mx-sm-3 mb-2">
  <%= f.text_field :name, class: "form-control"  %>
  </div>
  <%= f.submit t(".submit"), class: "btn btn-primary mb-2" %>
<% end %>

app/views/admin/locations/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="table-responsive">
      <div>
        <%= render "form" %>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th><%= t ".id" %></th>
            <th><%= t ".name" %></th>
          </tr>
        </thead>
        <tbody class="locations">
          <%= render @locations %>
        </tbody>
      </table>
      <%= paginate @locations %>
    </div>
  </div>
</div>