config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root "static_pages#home"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/index", to: "travellings#index"
  get "/show", to: "travellings#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  namespace :admin do
    root "static_pages#show"
    get "/locations", to: "locations#index"
    post "/locations", to: "locations#create"
    resources :users, only: %i(index destroy show)
    resources :locations, except: :show
    resources :travellings, except: :show
    resources :tours, except: :show
    resources :bookings, only: %i(index update)
    resources :export_users, only: :index
  end
  resources :users
  resources :travellings
  # resources :travellings do
  #   collection do
  #     match 'search' => "travellings#search", :via => [:get, :post], :as => :search
  #   end
  # end
  resources :tours
  resources :reviews

  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"

  resources :bookings, only: [:new, :create]
  delete "/delete", to: "bookings#destroy"
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :category
  belongs_to :travelling

  delegate :name, to: :category
  delegate :location_start, to: :travelling
  delegate :location_end, to: :travelling

  scope :order_new_tours, ->{order created_at: :desc}
  scope :search_tour_by_travelling_id, (lambda do |travelling_ids|
    where travelling_id: travelling_ids if travelling_ids
  end)
  scope :where_time_start, ->(time_start){where "time_start >= ?", time_start}
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::AdminBaseController
  before_action :check_permission
  before_action :load_tour, only: %i(edit update destroy)
  before_action :load_travellings, only: %i(new edit)

  def index
    @tours =
      Tour.preload(:travelling).order_new_tours.page(params[:page])
  end

  def new
    @tour = Tour.new
    @categories = Category.all
  end

  def create
    @tour = Tour.new tour_params
    if @tour.save
      flash[:success] = t "add_tour_sucess"
      redirect_to admin_tours_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @tour.update_attributes tour_params
      flash[:success] = t "update_tour_success"
      redirect_to admin_tours_path
    else
      flash[:danger] = t "update_tour_failed"
    end
  end

  def destroy
    if @tour.bookings.blank? == false
      flash[:danger] = t "del_tour_failed"
      redirect_to request.referrer
    elsif @tour.destroy
      flash[:success] = t "del_tour_success"
      respond_to do |format|
        format.js
      end
    else
      flash[:danger] = t "del_tour_failed"
      redirect_to request.referrer
    end
  end

  private

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "err_tour"
    redirect_to admin_tours_path
  end

  def tour_params
    params.require(:tour).permit :category_id, :travelling_id, :price,
      :time_start, :time_end, :max_quantity
  end

  def load_travellings
    @travellings = Travelling.all.map do |e|
      ["#{e.start_name} - #{e.end_name}", e.id]
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :load_tour_details, :current_user, only: :show

  def show
    @reviews = @tour_details.reviews.to_a
    @avg_rating = @reviews.blank? ? 0 : @tour_details.reviews.average(:rating)
    @review  = current_user.reviews.build if user_signed_in?
    @reviews = @tour_details.reviews.order_reviews
    if request.xhr?
      render json: {
        addresses: @tour_details.travelling.location_end
      }
    end
  end

  private

  def load_tour_details
    @tour_details = Tour.find_by id: params[:id]
    return if @tour_details
    flash[:danger] = t "no_data"
    redirect_to tour_path
  end
end

app/helpers/tours_helper.rb
module ToursHelper
  def count_date end1, start1
    (end1.to_date - start1.to_date).to_i
  end

  def check_time_start time_start
    time_start >= Date.current
  end

  def check_booking_quantity max, recent
    (max - recent).positive?
  end
end

app/views/admin/tours/_tour.html.erb
<tr id="delete_tour_<%= tour.id %>">
  <td><%= tour.id %></td>
  <td><%= tour.name %></td>
  <td><%= number_to_currency(tour.price) %></td>
  <td>
    <%= tour.travelling.start_name %>
    -
    <%= tour.travelling.end_name %>
  </td>
  <td>
    <%= l tour.time_start, format: :date %>
    -
    <%= l tour.time_end, format: :date %>
  </td>
  <td><%= tour.max_quantity %></td>
  <td><%= tour.recent_quantity %></td>
  <td></td>
  <td>
    <%= link_to t(".edit"), edit_admin_tour_path(tour), class: "btn btn-warning" %>
  </td>
  <td>
    <%= link_to t(".del"), admin_tour_path(tour), method: :delete, remote: true, class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/tours/destroy.js.erb
$('#delete_tour_<%= @tour.id %>').remove();
<% flash.each do |message_type, message| %>
  $('#flash_messages').html("<div class='alert alert-<%= message_type %>'><%= message %>")
<% end %>

app/views/admin/tours/edit.html.erb
<div class="card">
  <div class="card-body">
   <%= form_for [:admin, @tour], html: {class: "form-sample"} do |f| %>
    <div class="form-group">
      <%= "category" %>
      <div class="form-radio">
        <%= f.radio_button :category_id, 1, checked: true %>
        <%= label :category_id, "domestic" %>
      </div>
      <div class="form-radio">
        <%= f.radio_button :category_id, 2 %>
        <%= label :category_id, "foreign" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :travelling, "travelling"%>
      <%= f.select :travelling_id, @travellings, {},{ class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :price, "price"%>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col">
          <%= f.label :time_start, "time_start" %>
          <%= f.datetime_field :time_start, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :time_start, "time_end" %>
          <%= f.datetime_field :time_end, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :max_quantity, "max_quantity"%>
      <%= f.text_field :max_quantity, class: "form-control" %>
    </div>
    <%= f.submit t(".submit"), class: "btn btn-success mr-2" %>
  <% end %>
  </div>
</div>

app/views/admin/tours/index.html.erb
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div>
        <%= link_to t(".click"), new_admin_tour_path, class: "btn btn-primary btn-lg" %>
      </div>
      <br>
      <div class="table-responsive">
        <table class="table table-bordered" id="index_tour">
          <thead>
            <tr>
              <th><%= t(".id") %></th>
              <th><%= t(".category") %></th>
              <th><%= t(".price") %></th>
              <th><%= t(".travelling") %></th>
              <th><%= t(".time") %></th>
              <th><%= t(".max") %></th>
              <th><%= t(".recent") %></th>
              <th><%= t(".rating") %></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @tours %>
          </tbody>
        </table>
        <%= paginate @tours %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tours/new.html.erb
<div class="card">
  <div class="card-body">
   <%= form_for [:admin, @tour], html: {class: "form-sample"} do |f| %>
    <div class="form-group">
      <%= "category" %>
      <div class="form-radio">
        <%= f.radio_button :category_id, 1, checked: true %>
        <%= label :category_id, "domestic" %>
      </div>
      <div class="form-radio">
        <%= f.radio_button :category_id, 2 %>
        <%= label :category_id, "foreign" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :travelling, "travelling"%>
      <%= f.select :travelling_id, @travellings, {},{ class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :price, "price"%>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col">
          <%= f.label :time_start, "time_start" %>
          <%= f.datetime_field :time_start, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :time_start, "time_end" %>
          <%= f.datetime_field :time_end, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :max_quantity, "max_quantity"%>
      <%= f.text_field :max_quantity, class: "form-control" %>
    </div>
    <%= f.submit t(".submit"), class: "btn btn-success mr-2" %>
  <% end %>
  </div>
</div>