config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root "static_pages#home"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/index", to: "travellings#index"
  get "/show", to: "travellings#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  namespace :admin do
    root "static_pages#show"
    get "/locations", to: "locations#index"
    post "/locations", to: "locations#create"
    resources :users, only: %i(index destroy show)
    resources :locations, except: :show
    resources :travellings, except: :show
    resources :tours, except: :show
    resources :bookings, only: %i(index update)
    resources :export_users, only: :index
  end
  resources :users
  resources :travellings
  # resources :travellings do
  #   collection do
  #     match 'search' => "travellings#search", :via => [:get, :post], :as => :search
  #   end
  # end
  resources :tours
  resources :reviews

  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"

  resources :bookings, only: [:new, :create]
  delete "/delete", to: "bookings#destroy"
end

app/models/travelling.rb
class Travelling < ApplicationRecord
  has_many :tours
  belongs_to :location_start, class_name: Location.name,
    foreign_key: :location_start_id
  belongs_to :location_end, class_name: Location.name,
    foreign_key: :location_end_id

  delegate :name, to: :location_start, prefix: :start
  delegate :name, to: :location_end, prefix: :end

  scope :ordered_by_created, ->{order created_at: :desc}

  scope :group_travellings, ->{group :location_end_id}
  scope :where_travellings, ->(id){where location_end_id: id}
end

app/controllers/admin/travellings_controller.rb
class Admin::TravellingsController < Admin::AdminBaseController
  before_action :check_permission
  before_action :load_travelling, only: %i(edit update destroy)
  before_action :load_locations, only: %i(edit new)

  def index
    @travellings = Travelling.ordered_by_created.page(params[:page])
  end

  def edit; end

  def update
    if @travelling.update_attributes travelling_params
      flash[:success] = t "update_travelling_success"
      redirect_to admin_travellings_path
    else
      flash[:danger] = t "update_travelling_failed"
    end
  end

  def destroy
    respond_to do |format|
      if @travelling.destroy
        flash[:success] = t "del_travelling_success"
      else
        flash[:danger] = t "del_travelling_failed"
      end
      format.js
    end
  end

  def new
    @travelling = Travelling.new
  end

  def create
    @travelling = Travelling.new travelling_params
    if @travelling.save
      flash[:success] = t "add_travelling_success"
      redirect_to admin_travellings_path
    else
      render :new
    end
  end

  private

  def load_travelling
    @travelling = Travelling.find_by id: params[:id]
    return if @travelling
    flash[:danger] = t "err_location"
    redirect_to admin_travellings_path
  end

  def load_locations
    @locations = Location.all.map{|e| [e.name, e.id]}
  end

  def travelling_params
    params.require(:travelling).permit :location_start_id, :location_end_id
  end
end

app/controllers/travellings_controller.rb
class TravellingsController < ApplicationController
  def index
    @travellings = Travelling.all.group_travellings
    @travelling = if params[:location_end_id]
                    Travelling.where_travellings(params[:location_end_id])
                  else
                    Travelling.all
                  end
    @q = Tour.search(params[:q])
    if params[:q]
      @tours = @q.result.page(params[:page])
    else
      @tours = Tour.search_tour_by_travelling_id(@travelling.pluck(:id))
        .where_time_start(Date.current).page(params[:page])
    end
  end
end

app/views/admin/travellings/_travelling.html.erb
<tr id="delete_travelling_<%= travelling.id %>">
  <td><%= travelling.id %></td>
  <td><%= travelling.start_name %></td>
  <td><%= travelling.end_name %></td>
  <td>
    <%= link_to t(".edit"), edit_admin_travelling_path(travelling), class: "btn btn-warning"  %>
  </td>
  <td>
    <%= link_to t(".del"), admin_travelling_path(travelling), method: :delete, remote: true, class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/travellings/destroy.js.erb
$("#delete_travelling_<%= @travelling.id %>").remove();
<% flash.each do |message_type, message| %>
  $("#flash_messages").html("<div class='alert alert-<%= message_type %>'><%= message %>")
<% end %>

app/views/admin/travellings/edit.html.erb
<div class="card-body">
  <%= form_for [:admin, @travelling], html: {class: "form-sample"} do |f| %>
    <div class="form-group">
      <%= f.label :name, t(".start")%>
      <%= f.select :location_start_id, @locations, {selected: [@travelling.location_start.name, @travelling.location_start.id]}, { class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :name, t(".end")%>
      <%= f.select :location_end_id, @locations, {selected: [@travelling.location_end.name, @travelling.location_end.id]}, { class: "form-control"} %>
    </div>
    <%= f.submit t(".submit"), class: "btn btn-success mr-2" %>
  <% end %>
</div>

app/views/admin/travellings/index.html.erb
<div class="card">
  <div class="card-body">
    <div>
      <%= link_to t(".click"), new_admin_travelling_path, class: "btn btn-primary btn-lg" %>
    </div>
    <br>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th><%= t ".id" %></th>
            <th><%= t ".start" %></th>
            <th><%= t ".end" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @travellings %>
        </tbody>
      </table>
      <%= paginate @travellings %>
    </div>
  </div>
</div>

app/views/admin/travellings/new.html.erb
<div class="card">
  <div class="card-body">
    <%= form_for [:admin, @travelling], html: {class: "form-sample"} do |f| %>
      <div class="form-group">
        <%= f.label :name, t(".start")%>
        <%= f.select :location_start_id, @locations, {selected: @locations.first}, { class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :name, t(".end")%>
        <%= f.select :location_end_id, @locations, {selected: @locations.second},
          {class: "form-control"} %>
      </div>
      <%= f.submit t(".submit"), class: "btn btn-success mr-2" %>
    <% end %>
  </div>
</div>