config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root "static_pages#home"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/index", to: "travellings#index"
  get "/show", to: "travellings#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  namespace :admin do
    root "static_pages#show"
    get "/locations", to: "locations#index"
    post "/locations", to: "locations#create"
    resources :users, only: %i(index destroy show)
    resources :locations, except: :show
    resources :travellings, except: :show
    resources :tours, except: :show
    resources :bookings, only: %i(index update)
    resources :export_users, only: :index
  end
  resources :users
  resources :travellings
  # resources :travellings do
  #   collection do
  #     match 'search' => "travellings#search", :via => [:get, :post], :as => :search
  #   end
  # end
  resources :tours
  resources :reviews

  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"

  resources :bookings, only: [:new, :create]
  delete "/delete", to: "bookings#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :validatable, :confirmable, :omniauthable, omniauth_providers: %i[facebook]
  CSV_ATTRIBUTES = %w(name email phonenumber).freeze
  has_many :bookings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  before_save :downcase_email

  enum role: {user: 0, admin: 1}

  scope :all_except, ->(user){where.not(id: user)}
  scope :ordered_by_name, ->{order name: :desc}

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email =
        "#{auth.info.name}@#{auth.provider}.com".downcase.gsub(/\s+/, "")
      user.password = Devise.friendly_token[6, 20]
      user.name = auth.info.name
      user.confirmed_at = Time.now
      user.provider = auth.provider
      user.uid = auth.uid
    end
  end

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminBaseController
  before_action :check_permission
  before_action :load_user, only: %i(destroy show)

  def show
    @bookings = @user.bookings.page(params[:page]).per(5)
    @sum = 0
  end

  def index
    @users = User.all_except(current_user).page(params[:page])
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        flash[:success] = t "del_user_success"
      else
        flash[:danger] = t "del_user_failed"
      end
      format.js
    end
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "err_user"
    redirect_to admin_users_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @booking = Booking.where(user_id: current_user.id)
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "msg_success"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :phonenumber, :password,
      :password_confirmation
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for user, size: Settings.size
    md5 = Digest::MD5.new
    gravatar_id = md5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/_user.html.erb
<tr id="delete_user_<%= user.id %>">
  <td><%= user.id %></td>
  <td><%= user.email %></td>
  <td><%= user.phonenumber %></td>
  <td>
    <%= link_to t(".del"), admin_user_path(user), method: :delete, remote: true, class: "btn btn-danger" %>
  </td>
  <th>
    <%= link_to t(".details"), admin_user_path(user), class: "btn btn-info" %>
  </th>
</tr>

app/views/admin/users/destroy.js.erb
$('#delete_user_<%= @user.id %>').remove();
<% flash.each do |message_type, message| %>
  $('#flash_messages').html("<div class='alert alert-<%= message_type %>'><%= message %>")
<% end %>

app/views/admin/users/index.html.erb
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div>
         <%= link_to t(".link_export"), admin_export_users_path(format: :csv), class: "btn btn-primary btn-lg" %>
      </div>
      <br>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= t ".id" %></th>
              <th><%= t ".email" %></th>
              <th><%= t ".phonenumber" %></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @users %>
          </tbody>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" style=" text-align: center">
          <thead>
            <tr>
              <th><%= t(".tour_id") %></th>
              <th><%= t(".quantity") %></th>
              <th><%= t(".status") %></th>
              <th><%= t(".bill") %></th>
            </tr>
          </thead>
          <tbody>
            <% @bookings.each do |t| %>
              <tr>
                <% @sum += t.bill %>
                <td><%= t.tour.id%></td>
                <td><%= t.quantity %></td>
                <td><%= t.status %></td>
                <td><%= number_to_currency(t.bill) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <div>
        <p class="btn btn-info"><%= "Tổng hóa đơn: #{number_to_currency(@sum)}" %></p>
      </div>
        <%= paginate @bookings %>
      </div>
    </div>
  </div>
</div>